[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_vault = "J6Fc9DF2SxEydxG7BZhB7CZybPxSTnfo27r6Z8RyVuJb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/Minh_Nguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
